### ISSUE TITLE
Auth Code Grant with "urn:ietf:wg:oauth:2.0:oob" as redirect url

### ISSUE THREAD

**Issue by lizardon** [charlesbihis/actionscript-oauth2#1]
if your using "urn:ietf:wg:oauth:2.0:oob" as the redirect URL, the auth code is returned in the title of the response page. 

So instead of parsing the redirect url in LocationChangeEvent.LOCATION_CHANGE. You need to parse the authorizationCodeGrant.stageWebView.title in Event.COMPLETE.

**Comment by charlesbihis** [comment]
This is actually a convenience feature specific to Google's implementation of the OAuth 2 protocol.  It isn't mentioned in the spec (as far as I can tell) and so I'm hesitant to add support for it in the library.

It was added as a feature for installed applications where the client does not have easy access to inspect the user agent.  This isn't the case in applications using this library.  So, the obvious fix for this (or workaround, depending on how you see it) would be to simply not use "urn:ietf:wg:oauth:2.0:oob" as a redirect URI.  Use "http://localhost" instead.

**Comment by charlesbihis** [comment]
After trying out the alternate method I suggested above, it looks like it uncovered a pretty gnarly AIR SDK bug.  So, rather than leave the library in a state where it doesn't work with Google's OAuth 2 implementation and custom workflow for installed applications, I added support for it as suggested with the initial open issue.

Fixed in commit [b4f3384bb5bc06b272323a2c66c375c111af4346](https://github.com/charlesbihis/actionscript-oauth2/commit/b4f3384bb5bc06b272323a2c66c375c111af4346)
