### ISSUE TITLE
StageWebView Events 

### ISSUE THREAD

**Issue by lizardon** [charlesbihis/actionscript-oauth2#4]
It would be nice if the OAuth2 class could fire off events to notify of StageWebView events. In particular a Load URI event and a Finished With StageWebView event. This is necessary because the StageWebView itself does not have a Load URI event. It only has a Change and Changing events. Knowing when a URI begins loading is necessary to implement a loading indicator. Also a Finished with StageWebView event  (or a GetAuthCodeEvent) would be nice to have so the app can close the StageWebView as soon as possible. This is particularly the case with installed apps, where the SageWebView will stay open awkwardly after completing the login, while the oauth token is retrieved in the second step.

Thanks for taking a look at this issue. But I would like to clarify why these changes would be helpful. First off these are really only issues that would become serious when a user has a slow or unreliable internet connection. For this case I have been implementing a loading indicator, so the user knows there is no need to keep pressing submit. Also, at least in the case of the Google Installed App OAuth use case, the result page that shows once an auth code is obtained but before an access token, if it stays visible for more than a second it is misleading and confusing to the user because it instructs the user to copy and paste the code. This is why it would be nice to close the StageWebView as soon as possible.

As to the difference between locationChange, locationChanging and loadURL:
locationChange is fired when the page load is complete.
locationChanging is fired when page starts loading but is not fired when loadURL initiates that change. From the docs: "A locationChanging event is only dispatched when the location change is initiated through HTML content or code running inside the StageWebView object,such as when a user clicks a link. "

To implement a loading indicator, I have found that I need to know when loadURL is called, because no event is raised otherwise.

With regard to listening for a GetAccessTokenEvent: 
The GetAccessTokenEvent is not fired when the auth code is obtained. But rather there is a delay between when the auth code is obtained and the access token is granted while a call to the tokenEndpoint is made. Usually this is fast and unnoticeable, but in the case of slow or unreliable internet it can cause the auth code result page to linger, leading to confusion. It would be nice to know when the auth code process is complete so the WebStageView can be closed.

Admittedly these are not urgent issues, but these improvements will enable an enhanced user experience.

**Comment by charlesbihis** [comment]
Thanks for clarifying your issue.  After thinking about this some more, though, I'm not sure that these enhancements would make this library more usable.  All of the things that you are trying to achieve can be done without adding any new events.

You would like you implement a loading indicator, and for this, you would like 2 events: one to notify you of when the StageWebView starts loading the user-consent screen, and a subsequent one for when the StageWebView receives the authorization code (but before it exchanges this for an access token).  Here's how you can do this...

Start loading indicator:
The loading of the user-consent form is controlled by the client (i.e. your application).  I'm guessing this is a "login" button, or something similar.  Instead of relying on a load-event from the library to fire, you can simply display your loading indicator when the login button is pushed.  Or, more precisely, when you call OAuth2.getAccessToken().

End loading indicator:
You would like to end the display of your loading indicator once you've received the authorization code, and not when you receive the access token.  This event makes more sense to include.  However, for the sake of abstraction, I think it may be better to leave this out (at least for now - if more people find this useful, then it can be added).  You can find out when the authorization code is received on your own as well.  Simply attach a LocationChangeEvent to the StageWebView object you pass into the library and detect when it hits your redirect URI.  Once this happens, you can verify the presence of the authorization code and stop your loading indicator (see lines 260-286 in com.adobe.protocols.oauth2.OAuth2.as for how it's done in the library).

Anyways, hope this helps.  And if you do happen to still want these changes, feel free to make them and submit a pull request!
